id: P001780
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74532
  title: སྡེ་བདུན་གྱི་རྒྱན་ཡིད་ཀྱི་མུན་སེལ།
  author: ''
  volumes:
    d262ab8bd99d4128b669438b19b75704:
      image_group_id: I4CZ74534
      title: ''
      volume_number: 1
      total_pages: 698
      base_file: v001.txt
