id: P001780
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:21:12.129977
source_metadata:
  id: bdr:W4CZ74532
  title: སྡེ་བདུན་གྱི་རྒྱན་ཡིད་ཀྱི་མུན་སེལ།
  author: ''
  volumes:
    d262ab8bd99d4128b669438b19b75704:
      image_group_id: I4CZ74534
      title: ''
      volume_number: 1
      total_pages: 698
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
